/**
 * Enums y constantes para validadores CDR
 */

// Reuse from sessionValidators
const TOKEN_TYPES = ['AD_HOC_USER', 'APP_USER', 'OTHER', 'RFID'];
const AUTH_METHODS = ['AUTH_REQUEST', 'COMMAND', 'WHITELIST'];

// ConnectorType enum (8.4.5)
const CONNECTOR_TYPES = [
  'CHADEMO',
  'DOMESTIC_A', 'DOMESTIC_B', 'DOMESTIC_C', 'DOMESTIC_D', 'DOMESTIC_E',
  'DOMESTIC_F', 'DOMESTIC_G', 'DOMESTIC_H', 'DOMESTIC_I', 'DOMESTIC_J',
  'DOMESTIC_K', 'DOMESTIC_L',
  'IEC_60309_2_single_16', 'IEC_60309_2_three_16', 'IEC_60309_2_three_32', 'IEC_60309_2_three_64',
  'IEC_62196_T1', 'IEC_62196_T1_COMBO', 'IEC_62196_T2', 'IEC_62196_T2_COMBO',
  'IEC_62196_T3A', 'IEC_62196_T3C',
  'PANTOGRAPH_BOTTOM_UP', 'PANTOGRAPH_TOP_DOWN',
  'TESLA_R', 'TESLA_S'
];

// ConnectorFormat enum (8.4.4)
const CONNECTOR_FORMATS = ['SOCKET', 'CABLE'];

// PowerType enum (8.4.19)
const POWER_TYPES = ['AC_1_PHASE', 'AC_3_PHASE', 'DC'];

// TariffType enum (11.4.7)
const TARIFF_TYPES = ['AD_HOC_PAYMENT', 'PROFILE_CHEAP', 'PROFILE_FAST', 'PROFILE_GREEN', 'REGULAR'];

// TariffDimensionType enum (11.4.5)
const TARIFF_DIMENSION_TYPES = ['ENERGY', 'FLAT', 'PARKING_TIME', 'TIME'];

// DayOfWeek enum (11.4.1)
const DAYS_OF_WEEK = ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'];

// ReservationRestrictionType enum (11.4.3)
const RESERVATION_RESTRICTION_TYPES = ['RESERVATION', 'RESERVATION_EXPIRES'];

// EnergySourceCategory enum (8.4.8)
const ENERGY_SOURCE_CATEGORIES = ['NUCLEAR', 'GENERAL_FOSSIL', 'COAL', 'GAS', 'GENERAL_GREEN', 'SOLAR', 'WIND', 'WATER'];

// EnvironmentalImpactCategory enum (8.4.10)
const ENVIRONMENTAL_IMPACT_CATEGORIES = ['NUCLEAR_WASTE', 'CARBON_DIOXIDE'];

// CdrDimension types (same as in sessionValidators)
const CDR_DIMENSION_TYPES = [
  'CURRENT', 'ENERGY', 'ENERGY_EXPORT', 'ENERGY_IMPORT', 'MAX_CURRENT',
  'MIN_CURRENT', 'MAX_POWER', 'MIN_POWER', 'PARKING_TIME', 'POWER',
  'RESERVATION_TIME', 'STATE_OF_CHARGE', 'TIME'
];

module.exports = {
  TOKEN_TYPES,
  AUTH_METHODS,
  CONNECTOR_TYPES,
  CONNECTOR_FORMATS,
  POWER_TYPES,
  TARIFF_TYPES,
  TARIFF_DIMENSION_TYPES,
  DAYS_OF_WEEK,
  RESERVATION_RESTRICTION_TYPES,
  ENERGY_SOURCE_CATEGORIES,
  ENVIRONMENTAL_IMPACT_CATEGORIES,
  CDR_DIMENSION_TYPES
};

