/**
 * Enums y constantes para validadores Location
 */

// Reuse from other validators
const TOKEN_TYPES = ['AD_HOC_USER', 'APP_USER', 'OTHER', 'RFID'];

// ParkingType enum (8.4.18)
const PARKING_TYPES = [
  'ALONG_MOTORWAY', 'PARKING_GARAGE', 'PARKING_LOT', 'ON_DRIVEWAY',
  'ON_STREET', 'UNDERGROUND_GARAGE'
];

// Status enum (8.4.22)
const STATUSES = [
  'AVAILABLE', 'BLOCKED', 'CHARGING', 'INOPERATIVE', 'OUTOFORDER',
  'PLANNED', 'REMOVED', 'RESERVED', 'UNKNOWN'
];

// Capability enum (8.4.3)
const CAPABILITIES = [
  'CHARGING_PROFILE_CAPABLE', 'CHARGING_PREFERENCES_CAPABLE',
  'CHIP_CARD_SUPPORT', 'CONTACTLESS_CARD_SUPPORT',
  'CREDIT_CARD_PAYABLE', 'DEBIT_CARD_PAYABLE',
  'PED_TERMINAL', 'REMOTE_START_STOP_CAPABLE',
  'RESERVABLE', 'RFID_READER', 'TOKEN_GROUP_CAPABLE', 'UNLOCK_CAPABLE'
];

// ConnectorType enum (8.4.5)
const CONNECTOR_TYPES = [
  'CHADEMO',
  'DOMESTIC_A', 'DOMESTIC_B', 'DOMESTIC_C', 'DOMESTIC_D', 'DOMESTIC_E',
  'DOMESTIC_F', 'DOMESTIC_G', 'DOMESTIC_H', 'DOMESTIC_I', 'DOMESTIC_J',
  'DOMESTIC_K', 'DOMESTIC_L',
  'IEC_60309_2_single_16', 'IEC_60309_2_three_16', 'IEC_60309_2_three_32', 'IEC_60309_2_three_64',
  'IEC_62196_T1', 'IEC_62196_T1_COMBO', 'IEC_62196_T2', 'IEC_62196_T2_COMBO',
  'IEC_62196_T3A', 'IEC_62196_T3C',
  'PANTOGRAPH_BOTTOM_UP', 'PANTOGRAPH_TOP_DOWN',
  'TESLA_R', 'TESLA_S'
];

// ConnectorFormat enum (8.4.4)
const CONNECTOR_FORMATS = ['SOCKET', 'CABLE'];

// PowerType enum (8.4.19)
const POWER_TYPES = ['AC_1_PHASE', 'AC_3_PHASE', 'DC'];

// ParkingRestriction enum (8.4.17)
const PARKING_RESTRICTIONS = ['EV_ONLY', 'PLUGGED', 'DISABLED', 'CUSTOMERS', 'MOTORCYCLES'];

// Facility enum (8.4.12)
const FACILITIES = [
  'HOTEL', 'RESTAURANT', 'CAFE', 'MALL', 'SUPERMARKET', 'SPORT',
  'RECREATION_AREA', 'NATURE', 'MUSEUM', 'BIKE_SHARING', 'BUS_STOP',
  'TAXI_STAND', 'TRAM_STOP', 'METRO_STATION', 'TRAIN_STATION',
  'AIRPORT', 'PARKING_LOT', 'CARPOOL_PARKING', 'FUEL_STATION', 'WIFI'
];

// ImageCategory enum (8.4.16)
const IMAGE_CATEGORIES = [
  'CHARGER', 'ENTRANCE', 'LOCATION', 'NETWORK', 'OPERATOR', 'OTHER', 'OWNER'
];

module.exports = {
  TOKEN_TYPES,
  PARKING_TYPES,
  STATUSES,
  CAPABILITIES,
  CONNECTOR_TYPES,
  CONNECTOR_FORMATS,
  POWER_TYPES,
  PARKING_RESTRICTIONS,
  FACILITIES,
  IMAGE_CATEGORIES
};

