-- Script para insertar EVSEs en las 10 ubicaciones de España
-- Fecha: 2025-09-01

-- EVSEs para MADRID - Plaza Norte 2 (4 EVSEs)
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-MADRID-PN-EVSE-001', 'ES-IPD-MADRID-PLAZA-NORTE', 'ES', 'IPD', 'ES*IPD*PN001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "40.4168", "longitude": "-3.7038"}', 'Zona A - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-MADRID-PN-EVSE-002', 'ES-IPD-MADRID-PLAZA-NORTE', 'ES', 'IPD', 'ES*IPD*PN001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "40.4168", "longitude": "-3.7038"}', 'Zona A - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-MADRID-PN-EVSE-003', 'ES-IPD-MADRID-PLAZA-NORTE', 'ES', 'IPD', 'ES*IPD*PN001*003', 'CHARGING', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "40.4168", "longitude": "-3.7038"}', 'Zona A - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-MADRID-PN-EVSE-004', 'ES-IPD-MADRID-PLAZA-NORTE', 'ES', 'IPD', 'ES*IPD*PN001*004', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "4", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "40.4168", "longitude": "-3.7038"}', 'Zona A - Nivel 0', NOW(), NOW(), NOW());

-- EVSEs para BARCELONA - Diagonal Mar (5 EVSEs)
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-BARCELONA-DM-EVSE-001', 'ES-IPD-BARCELONA-DIAGONAL-MAR', 'ES', 'IPD', 'ES*IPD*DM001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.3851", "longitude": "2.1734"}', 'Zona B - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BARCELONA-DM-EVSE-002', 'ES-IPD-BARCELONA-DIAGONAL-MAR', 'ES', 'IPD', 'ES*IPD*DM001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.3851", "longitude": "2.1734"}', 'Zona B - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BARCELONA-DM-EVSE-003', 'ES-IPD-BARCELONA-DIAGONAL-MAR', 'ES', 'IPD', 'ES*IPD*DM001*003', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.3851", "longitude": "2.1734"}', 'Zona B - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BARCELONA-DM-EVSE-004', 'ES-IPD-BARCELONA-DIAGONAL-MAR', 'ES', 'IPD', 'ES*IPD*DM001*004', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "4", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.3851", "longitude": "2.1734"}', 'Zona B - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BARCELONA-DM-EVSE-005', 'ES-IPD-BARCELONA-DIAGONAL-MAR', 'ES', 'IPD', 'ES*IPD*DM001*005', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "5", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.3851", "longitude": "2.1734"}', 'Zona B - Nivel 0', NOW(), NOW(), NOW());

-- EVSEs para VALENCIA - Aqua Multiespacio (6 EVSEs)
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-VALENCIA-AQUA-EVSE-001', 'ES-IPD-VALENCIA-AQUA', 'ES', 'IPD', 'ES*IPD*AQ001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "39.4699", "longitude": "-0.3763"}', 'Zona C - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-VALENCIA-AQUA-EVSE-002', 'ES-IPD-VALENCIA-AQUA', 'ES', 'IPD', 'ES*IPD*AQ001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "39.4699", "longitude": "-0.3763"}', 'Zona C - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-VALENCIA-AQUA-EVSE-003', 'ES-IPD-VALENCIA-AQUA', 'ES', 'IPD', 'ES*IPD*AQ001*003', 'CHARGING', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "39.4699", "longitude": "-0.3763"}', 'Zona C - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-VALENCIA-AQUA-EVSE-004', 'ES-IPD-VALENCIA-AQUA', 'ES', 'IPD', 'ES*IPD*AQ001*004', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "4", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "39.4699", "longitude": "-0.3763"}', 'Zona C - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-VALENCIA-AQUA-EVSE-005', 'ES-IPD-VALENCIA-AQUA', 'ES', 'IPD', 'ES*IPD*AQ001*005', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "5", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "39.4699", "longitude": "-0.3763"}', 'Zona C - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-VALENCIA-AQUA-EVSE-006', 'ES-IPD-VALENCIA-AQUA', 'ES', 'IPD', 'ES*IPD*AQ001*006', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "6", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "39.4699", "longitude": "-0.3763"}', 'Zona C - Nivel 0', NOW(), NOW(), NOW());

-- EVSEs para SEVILLA - Plaza de Armas (3 EVSEs)
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-SEVILLA-PA-EVSE-001', 'ES-IPD-SEVILLA-PLAZA-ARMAS', 'ES', 'IPD', 'ES*IPD*PA001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "37.3891", "longitude": "-5.9845"}', 'Zona D - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-SEVILLA-PA-EVSE-002', 'ES-IPD-SEVILLA-PLAZA-ARMAS', 'ES', 'IPD', 'ES*IPD*PA001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "37.3891", "longitude": "-5.9845"}', 'Zona D - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-SEVILLA-PA-EVSE-003', 'ES-IPD-SEVILLA-PLAZA-ARMAS', 'ES', 'IPD', 'ES*IPD*PA001*003', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "37.3891", "longitude": "-5.9845"}', 'Zona D - Nivel 0', NOW(), NOW(), NOW());
