-- Script para generar 10 zonas con EVSEs en ESP
-- Usando ubicaciones y coordenadas reales
-- Fecha: 2025-09-01

-- Limpiar datos existentes (opcional)
-- DELETE FROM evses WHERE location_id IN (SELECT id FROM locations WHERE country = 'ESP' AND city IN ('Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao', 'Málaga', 'Zaragoza', 'Granada', 'Alicante', 'Valladolid'));
-- DELETE FROM locations WHERE country = 'ESP' AND city IN ('Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao', 'Málaga', 'Zaragoza', 'Granada', 'Alicante', 'Valladolid');

-- 1. MADRID - Centro Comercial Plaza Norte 2
INSERT INTO locations (id, country_code, party_id, name, address, city, postal_code, state, country, coordinates, parking_type, last_updated, created_at, updated_at) VALUES
('ES-IPD-MADRID-PLAZA-NORTE', 'ES', 'IPD', 'Plaza Norte 2 - Estación de Carga', 'Calle de la Viña, 3', 'Madrid', '28050', 'Madrid', 'ESP', '{"latitude": "40.4168", "longitude": "-3.7038"}', 'PARKING_GARAGE', NOW(), NOW(), NOW());

-- EVSEs para Madrid
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-MADRID-PN-EVSE-001', 'ES-IPD-MADRID-PLAZA-NORTE', 'ES', 'IPD', 'ES*IPD*PN001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "40.4168", "longitude": "-3.7038"}', 'Zona A - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-MADRID-PN-EVSE-002', 'ES-IPD-MADRID-PLAZA-NORTE', 'ES', 'IPD', 'ES*IPD*PN001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "40.4168", "longitude": "-3.7038"}', 'Zona A - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-MADRID-PN-EVSE-003', 'ES-IPD-MADRID-PLAZA-NORTE', 'ES', 'IPD', 'ES*IPD*PN001*003', 'CHARGING', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "40.4168", "longitude": "-3.7038"}', 'Zona A - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-MADRID-PN-EVSE-004', 'ES-IPD-MADRID-PLAZA-NORTE', 'ES', 'IPD', 'ES*IPD*PN001*004', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "4", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "40.4168", "longitude": "-3.7038"}', 'Zona A - Nivel 0', NOW(), NOW(), NOW());

-- 2. BARCELONA - Centro Comercial Diagonal Mar
INSERT INTO locations (id, country_code, party_id, name, address, city, postal_code, state, country, coordinates, parking_type, last_updated, created_at, updated_at) VALUES
('ES-IPD-BARCELONA-DIAGONAL-MAR', 'ES', 'IPD', 'Diagonal Mar - Estación de Carga', 'Passeig del Taulat, 262-264', 'Barcelona', '08019', 'Barcelona', 'ESP', '{"latitude": "41.3851", "longitude": "2.1734"}', 'PARKING_GARAGE', NOW(), NOW(), NOW());

-- EVSEs para Barcelona
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-BARCELONA-DM-EVSE-001', 'ES-IPD-BARCELONA-DIAGONAL-MAR', 'ES', 'IPD', 'ES*IPD*DM001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.3851", "longitude": "2.1734"}', 'Zona B - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BARCELONA-DM-EVSE-002', 'ES-IPD-BARCELONA-DIAGONAL-MAR', 'ES', 'IPD', 'ES*IPD*DM001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.3851", "longitude": "2.1734"}', 'Zona B - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BARCELONA-DM-EVSE-003', 'ES-IPD-BARCELONA-DIAGONAL-MAR', 'ES', 'IPD', 'ES*IPD*DM001*003', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.3851", "longitude": "2.1734"}', 'Zona B - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BARCELONA-DM-EVSE-004', 'ES-IPD-BARCELONA-DIAGONAL-MAR', 'ES', 'IPD', 'ES*IPD*DM001*004', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "4", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.3851", "longitude": "2.1734"}', 'Zona B - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BARCELONA-DM-EVSE-005', 'ES-IPD-BARCELONA-DIAGONAL-MAR', 'ES', 'IPD', 'ES*IPD*DM001*005', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "5", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.3851", "longitude": "2.1734"}', 'Zona B - Nivel 0', NOW(), NOW(), NOW());

-- 3. VALENCIA - Centro Comercial Aqua Multiespacio
INSERT INTO locations (id, country_code, party_id, name, address, city, postal_code, state, country, coordinates, parking_type, last_updated, created_at, updated_at) VALUES
('ES-IPD-VALENCIA-AQUA', 'ES', 'IPD', 'Aqua Multiespacio - Estación de Carga', 'Carrer de Menorca, 19', 'Valencia', '46023', 'Valencia', 'ESP', '{"latitude": "39.4699", "longitude": "-0.3763"}', 'PARKING_GARAGE', NOW(), NOW(), NOW());

-- EVSEs para Valencia
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-VALENCIA-AQUA-EVSE-001', 'ES-IPD-VALENCIA-AQUA', 'ES', 'IPD', 'ES*IPD*AQ001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "39.4699", "longitude": "-0.3763"}', 'Zona C - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-VALENCIA-AQUA-EVSE-002', 'ES-IPD-VALENCIA-AQUA', 'ES', 'IPD', 'ES*IPD*AQ001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "39.4699", "longitude": "-0.3763"}', 'Zona C - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-VALENCIA-AQUA-EVSE-003', 'ES-IPD-VALENCIA-AQUA', 'ES', 'IPD', 'ES*IPD*AQ001*003', 'CHARGING', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "39.4699", "longitude": "-0.3763"}', 'Zona C - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-VALENCIA-AQUA-EVSE-004', 'ES-IPD-VALENCIA-AQUA', 'ES', 'IPD', 'ES*IPD*AQ001*004', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "4", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "39.4699", "longitude": "-0.3763"}', 'Zona C - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-VALENCIA-AQUA-EVSE-005', 'ES-IPD-VALENCIA-AQUA', 'ES', 'IPD', 'ES*IPD*AQ001*005', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "5", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "39.4699", "longitude": "-0.3763"}', 'Zona C - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-VALENCIA-AQUA-EVSE-006', 'ES-IPD-VALENCIA-AQUA', 'ES', 'IPD', 'ES*IPD*AQ001*006', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "6", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "39.4699", "longitude": "-0.3763"}', 'Zona C - Nivel 0', NOW(), NOW(), NOW());

-- 4. SEVILLA - Centro Comercial Plaza de Armas
INSERT INTO locations (id, country_code, party_id, name, address, city, postal_code, state, country, coordinates, parking_type, last_updated, created_at, updated_at) VALUES
('ES-IPD-SEVILLA-PLAZA-ARMAS', 'ES', 'IPD', 'Plaza de Armas - Estación de Carga', 'Plaza de Armas, 1', 'Sevilla', '41001', 'Sevilla', 'ESP', '{"latitude": "37.3891", "longitude": "-5.9845"}', 'PARKING_GARAGE', NOW(), NOW(), NOW());

-- EVSEs para Sevilla
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-SEVILLA-PA-EVSE-001', 'ES-IPD-SEVILLA-PLAZA-ARMAS', 'ES', 'IPD', 'ES*IPD*PA001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "37.3891", "longitude": "-5.9845"}', 'Zona D - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-SEVILLA-PA-EVSE-002', 'ES-IPD-SEVILLA-PLAZA-ARMAS', 'ES', 'IPD', 'ES*IPD*PA001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "37.3891", "longitude": "-5.9845"}', 'Zona D - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-SEVILLA-PA-EVSE-003', 'ES-IPD-SEVILLA-PLAZA-ARMAS', 'ES', 'IPD', 'ES*IPD*PA001*003', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "37.3891", "longitude": "-5.9845"}', 'Zona D - Nivel 0', NOW(), NOW(), NOW());

-- 5. BILBAO - Centro Comercial Zubiarte
INSERT INTO locations (id, country_code, party_id, name, address, city, postal_code, state, country, coordinates, parking_type, last_updated, created_at, updated_at) VALUES
('ES-IPD-BILBAO-ZUBIARTE', 'ES', 'IPD', 'Zubiarte - Estación de Carga', 'Paseo Campo Volantín, 23', 'Bilbao', '48007', 'Vizcaya', 'ESP', '{"latitude": "43.2627", "longitude": "-2.9253"}', 'PARKING_GARAGE', NOW(), NOW(), NOW());

-- EVSEs para Bilbao
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-BILBAO-ZUB-EVSE-001', 'ES-IPD-BILBAO-ZUBIARTE', 'ES', 'IPD', 'ES*IPD*ZB001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "43.2627", "longitude": "-2.9253"}', 'Zona E - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BILBAO-ZUB-EVSE-002', 'ES-IPD-BILBAO-ZUBIARTE', 'ES', 'IPD', 'ES*IPD*ZB001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "43.2627", "longitude": "-2.9253"}', 'Zona E - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BILBAO-ZUB-EVSE-003', 'ES-IPD-BILBAO-ZUBIARTE', 'ES', 'IPD', 'ES*IPD*ZB001*003', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "43.2627", "longitude": "-2.9253"}', 'Zona E - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BILBAO-ZUB-EVSE-004', 'ES-IPD-BILBAO-ZUBIARTE', 'ES', 'IPD', 'ES*IPD*ZB001*004', 'CHARGING', '["RESERVABLE", "RENTABLE"]', '[{"id": "4", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "43.2627", "longitude": "-2.9253"}', 'Zona E - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BILBAO-ZUB-EVSE-005', 'ES-IPD-BILBAO-ZUBIARTE', 'ES', 'IPD', 'ES*IPD*ZB001*005', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "5", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "43.2627", "longitude": "-2.9253"}', 'Zona E - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BILBAO-ZUB-EVSE-006', 'ES-IPD-BILBAO-ZUBIARTE', 'ES', 'IPD', 'ES*IPD*ZB001*006', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "6", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "43.2627", "longitude": "-2.9253"}', 'Zona E - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BILBAO-ZUB-EVSE-007', 'ES-IPD-BILBAO-ZUBIARTE', 'ES', 'IPD', 'ES*IPD*ZB001*007', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "7", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "43.2627", "longitude": "-2.9253"}', 'Zona E - Nivel 0', NOW(), NOW(), NOW());

-- 6. MÁLAGA - Centro Comercial Larios
INSERT INTO locations (id, country_code, party_id, name, address, city, postal_code, state, country, coordinates, parking_type, last_updated, created_at, updated_at) VALUES
('ES-IPD-MALAGA-LARIOS', 'ES', 'IPD', 'Larios - Estación de Carga', 'Calle Larios, 1', 'Málaga', '29005', 'Málaga', 'ESP', '{"latitude": "36.7213", "longitude": "-4.4217"}', 'PARKING_GARAGE', NOW(), NOW(), NOW());

-- EVSEs para Málaga
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-MALAGA-LAR-EVSE-001', 'ES-IPD-MALAGA-LARIOS', 'ES', 'IPD', 'ES*IPD*LR001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "36.7213", "longitude": "-4.4217"}', 'Zona F - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-MALAGA-LAR-EVSE-002', 'ES-IPD-MALAGA-LARIOS', 'ES', 'IPD', 'ES*IPD*LR001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "36.7213", "longitude": "-4.4217"}', 'Zona F - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-MALAGA-LAR-EVSE-003', 'ES-IPD-MALAGA-LARIOS', 'ES', 'IPD', 'ES*IPD*LR001*003', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "36.7213", "longitude": "-4.4217"}', 'Zona F - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-MALAGA-LAR-EVSE-004', 'ES-IPD-MALAGA-LARIOS', 'ES', 'IPD', 'ES*IPD*LR001*004', 'CHARGING', '["RESERVABLE", "RENTABLE"]', '[{"id": "4", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "36.7213", "longitude": "-4.4217"}', 'Zona F - Nivel 0', NOW(), NOW(), NOW());
