-- Segunda parte del script para insertar EVSEs en las 10 ubicaciones de España
-- Continuación de generate_spain_evses.sql
-- Fecha: 2025-09-01

-- EVSEs para BILBAO - Zubiarte (7 EVSEs)
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-BILBAO-ZUB-EVSE-001', 'ES-IPD-BILBAO-ZUBIARTE', 'ES', 'IPD', 'ES*IPD*ZB001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "43.2627", "longitude": "-2.9253"}', 'Zona E - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BILBAO-ZUB-EVSE-002', 'ES-IPD-BILBAO-ZUBIARTE', 'ES', 'IPD', 'ES*IPD*ZB001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "43.2627", "longitude": "-2.9253"}', 'Zona E - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BILBAO-ZUB-EVSE-003', 'ES-IPD-BILBAO-ZUBIARTE', 'ES', 'IPD', 'ES*IPD*ZB001*003', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "43.2627", "longitude": "-2.9253"}', 'Zona E - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BILBAO-ZUB-EVSE-004', 'ES-IPD-BILBAO-ZUBIARTE', 'ES', 'IPD', 'ES*IPD*ZB001*004', 'CHARGING', '["RESERVABLE", "RENTABLE"]', '[{"id": "4", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "43.2627", "longitude": "-2.9253"}', 'Zona E - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BILBAO-ZUB-EVSE-005', 'ES-IPD-BILBAO-ZUBIARTE', 'ES', 'IPD', 'ES*IPD*ZB001*005', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "5", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "43.2627", "longitude": "-2.9253"}', 'Zona E - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BILBAO-ZUB-EVSE-006', 'ES-IPD-BILBAO-ZUBIARTE', 'ES', 'IPD', 'ES*IPD*ZB001*006', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "6", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "43.2627", "longitude": "-2.9253"}', 'Zona E - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-BILBAO-ZUB-EVSE-007', 'ES-IPD-BILBAO-ZUBIARTE', 'ES', 'IPD', 'ES*IPD*ZB001*007', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "7", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "43.2627", "longitude": "-2.9253"}', 'Zona E - Nivel 0', NOW(), NOW(), NOW());

-- EVSEs para MÁLAGA - Larios (4 EVSEs)
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-MALAGA-LAR-EVSE-001', 'ES-IPD-MALAGA-LARIOS', 'ES', 'IPD', 'ES*IPD*LR001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "36.7213", "longitude": "-4.4217"}', 'Zona F - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-MALAGA-LAR-EVSE-002', 'ES-IPD-MALAGA-LARIOS', 'ES', 'IPD', 'ES*IPD*LR001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "36.7213", "longitude": "-4.4217"}', 'Zona F - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-MALAGA-LAR-EVSE-003', 'ES-IPD-MALAGA-LARIOS', 'ES', 'IPD', 'ES*IPD*LR001*003', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "36.7213", "longitude": "-4.4217"}', 'Zona F - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-MALAGA-LAR-EVSE-004', 'ES-IPD-MALAGA-LARIOS', 'ES', 'IPD', 'ES*IPD*LR001*004', 'CHARGING', '["RESERVABLE", "RENTABLE"]', '[{"id": "4", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "36.7213", "longitude": "-4.4217"}', 'Zona F - Nivel 0', NOW(), NOW(), NOW());

-- EVSEs para ZARAGOZA - Puerto Venecia (5 EVSEs)
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-ZARAGOZA-PV-EVSE-001', 'ES-IPD-ZARAGOZA-PUERTO-VENECIA', 'ES', 'IPD', 'ES*IPD*PV001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.6488", "longitude": "-0.8891"}', 'Zona G - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-ZARAGOZA-PV-EVSE-002', 'ES-IPD-ZARAGOZA-PUERTO-VENECIA', 'ES', 'IPD', 'ES*IPD*PV001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.6488", "longitude": "-0.8891"}', 'Zona G - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-ZARAGOZA-PV-EVSE-003', 'ES-IPD-ZARAGOZA-PUERTO-VENECIA', 'ES', 'IPD', 'ES*IPD*PV001*003', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.6488", "longitude": "-0.8891"}', 'Zona G - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-ZARAGOZA-PV-EVSE-004', 'ES-IPD-ZARAGOZA-PUERTO-VENECIA', 'ES', 'IPD', 'ES*IPD*PV001*004', 'CHARGING', '["RESERVABLE", "RENTABLE"]', '[{"id": "4", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.6488", "longitude": "-0.8891"}', 'Zona G - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-ZARAGOZA-PV-EVSE-005', 'ES-IPD-ZARAGOZA-PUERTO-VENECIA', 'ES', 'IPD', 'ES*IPD*PV001*005', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "5", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.6488", "longitude": "-0.8891"}', 'Zona G - Nivel 0', NOW(), NOW(), NOW());

-- EVSEs para GRANADA - Nevada (3 EVSEs)
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-GRANADA-NEV-EVSE-001', 'ES-IPD-GRANADA-NEVADA', 'ES', 'IPD', 'ES*IPD*NV001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "37.1765", "longitude": "-3.5976"}', 'Zona H - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-GRANADA-NEV-EVSE-002', 'ES-IPD-GRANADA-NEVADA', 'ES', 'IPD', 'ES*IPD*NV001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "37.1765", "longitude": "-3.5976"}', 'Zona H - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-GRANADA-NEV-EVSE-003', 'ES-IPD-GRANADA-NEVADA', 'ES', 'IPD', 'ES*IPD*NV001*003', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "37.1765", "longitude": "-3.5976"}', 'Zona H - Nivel 0', NOW(), NOW(), NOW());

-- EVSEs para ALICANTE - Gran Vía (5 EVSEs)
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-ALICANTE-GV-EVSE-001', 'ES-IPD-ALICANTE-GRAN-VIA', 'ES', 'IPD', 'ES*IPD*GV001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "38.3452", "longitude": "-0.4945"}', 'Zona I - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-ALICANTE-GV-EVSE-002', 'ES-IPD-ALICANTE-GRAN-VIA', 'ES', 'IPD', 'ES*IPD*GV001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "38.3452", "longitude": "-0.4945"}', 'Zona I - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-ALICANTE-GV-EVSE-003', 'ES-IPD-ALICANTE-GRAN-VIA', 'ES', 'IPD', 'ES*IPD*GV001*003', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "38.3452", "longitude": "-0.4945"}', 'Zona I - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-ALICANTE-GV-EVSE-004', 'ES-IPD-ALICANTE-GRAN-VIA', 'ES', 'IPD', 'ES*IPD*GV001*004', 'CHARGING', '["RESERVABLE", "RENTABLE"]', '[{"id": "4", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "38.3452", "longitude": "-0.4945"}', 'Zona I - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-ALICANTE-GV-EVSE-005', 'ES-IPD-ALICANTE-GRAN-VIA', 'ES', 'IPD', 'ES*IPD*GV001*005', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "5", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "38.3452", "longitude": "-0.4945"}', 'Zona I - Nivel 0', NOW(), NOW(), NOW());

-- EVSEs para VALLADOLID - Vallsur (4 EVSEs)
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, last_updated, created_at, updated_at) VALUES
('ES-IPD-VALLADOLID-VS-EVSE-001', 'ES-IPD-VALLADOLID-VALLSUR', 'ES', 'IPD', 'ES*IPD*VS001*001', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.6523", "longitude": "-4.7284"}', 'Zona J - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-VALLADOLID-VS-EVSE-002', 'ES-IPD-VALLADOLID-VALLSUR', 'ES', 'IPD', 'ES*IPD*VS001*002', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.6523", "longitude": "-4.7284"}', 'Zona J - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-VALLADOLID-VS-EVSE-003', 'ES-IPD-VALLADOLID-VALLSUR', 'ES', 'IPD', 'ES*IPD*VS001*003', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.6523", "longitude": "-4.7284"}', 'Zona J - Nivel 0', NOW(), NOW(), NOW()),
('ES-IPD-VALLADOLID-VS-EVSE-004', 'ES-IPD-VALLADOLID-VALLSUR', 'ES', 'IPD', 'ES*IPD*VS001*004', 'AVAILABLE', '["RESERVABLE", "RENTABLE"]', '[{"id": "4", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', '0', '{"latitude": "41.6523", "longitude": "-4.7284"}', 'Zona J - Nivel 0', NOW(), NOW(), NOW());
