-- Insert test EVSEs for Madrid location
INSERT INTO evses (
  id,
  location_id,
  country_code,
  party_id,
  evse_id,
  status,
  capabilities,
  connectors,
  floor_level,
  coordinates,
  physical_reference,
  directions,
  parking_restrictions,
  group_id,
  last_updated,
  created_at,
  updated_at
) VALUES (
  'evse-001',
  'loc-001',
  'ES',
  'ES-CPO',
  'ES-CPO-MAD-001',
  'AVAILABLE',
  '["RESERVABLE", "RENTABLE"]',
  '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]',
  'P0',
  '{"latitude": 40.4168, "longitude": -3.7038}',
  'MAD-001',
  '{"text": "En el sótano del centro comercial, zona de parking"}',
  '[]',
  'madrid-group',
  NOW(),
  NOW(),
  NOW()
);

INSERT INTO evses (
  id,
  location_id,
  country_code,
  party_id,
  evse_id,
  status,
  capabilities,
  connectors,
  floor_level,
  coordinates,
  physical_reference,
  directions,
  parking_restrictions,
  group_id,
  last_updated,
  created_at,
  updated_at
) VALUES (
  'evse-002',
  'loc-001',
  'ES',
  'ES-CPO',
  'ES-CPO-MAD-002',
  'AVAILABLE',
  '["RESERVABLE"]',
  '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_1_PHASE", "max_voltage": 230, "max_amperage": 16, "max_electric_power": 3680}]',
  'P0',
  '{"latitude": 40.4168, "longitude": -3.7038}',
  'MAD-002',
  '{"text": "En el sótano del centro comercial, zona de parking"}',
  '[]',
  'madrid-group',
  NOW(),
  NOW(),
  NOW()
);

-- Insert test EVSEs for Barcelona location
INSERT INTO evses (
  id,
  location_id,
  country_code,
  party_id,
  evse_id,
  status,
  capabilities,
  connectors,
  floor_level,
  coordinates,
  physical_reference,
  directions,
  parking_restrictions,
  group_id,
  last_updated,
  created_at,
  updated_at
) VALUES (
  'evse-003',
  'loc-002',
  'ES',
  'ES-CPO',
  'ES-CPO-BCN-001',
  'AVAILABLE',
  '["RESERVABLE", "RENTABLE"]',
  '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]',
  'G',
  '{"latitude": 41.3851, "longitude": 2.1734}',
  'BCN-001',
  '{"text": "En la estación de servicio, zona de parking"}',
  '[]',
  'barcelona-group',
  NOW(),
  NOW(),
  NOW()
);

INSERT INTO evses (
  id,
  location_id,
  country_code,
  party_id,
  evse_id,
  status,
  capabilities,
  connectors,
  floor_level,
  coordinates,
  physical_reference,
  directions,
  parking_restrictions,
  group_id,
  last_updated,
  created_at,
  updated_at
) VALUES (
  'evse-004',
  'loc-002',
  'ES',
  'ES-CPO',
  'ES-CPO-BCN-002',
  'CHARGING',
  '["RESERVABLE"]',
  '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_1_PHASE", "max_voltage": 230, "max_amperage": 16, "max_electric_power": 3680}]',
  'G',
  '{"latitude": 41.3851, "longitude": 2.1734}',
  'BCN-002',
  '{"text": "En la estación de servicio, zona de parking"}',
  '[]',
  'barcelona-group',
  NOW(),
  NOW(),
  NOW()
);

-- Insert test EVSEs for Porto location
INSERT INTO evses (
  id,
  location_id,
  country_code,
  party_id,
  evse_id,
  status,
  capabilities,
  connectors,
  floor_level,
  coordinates,
  physical_reference,
  directions,
  parking_restrictions,
  group_id,
  last_updated,
  created_at,
  updated_at
) VALUES (
  'evse-005',
  'loc-003',
  'PT',
  'ES-CPO',
  'ES-CPO-PRT-001',
  'AVAILABLE',
  '["RESERVABLE", "RENTABLE"]',
  '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]',
  'P1',
  '{"latitude": 41.1579, "longitude": -8.6291}',
  'PRT-001',
  '{"text": "En el centro comercial, primer nivel de parking"}',
  '[]',
  'porto-group',
  NOW(),
  NOW(),
  NOW()
);
