-- Clear existing test data
DELETE FROM evses WHERE id LIKE 'evse-%';

-- Insert EVSEs distributed across locations (max 50 per location)
-- Madrid locations (10 locations, ~50 EVSEs each = ~500 EVSEs)
INSERT INTO evses (id, location_id, country_code, party_id, evse_id, status, capabilities, connectors, floor_level, coordinates, physical_reference, directions, parking_restrictions, group_id, last_updated, created_at, updated_at) VALUES
-- Location: loc-mad-001 (Centro Comercial Plaza Norte 2)
('evse-mad-001-001', 'loc-mad-001', 'ES', 'ES-CPO', 'ES-CPO-MAD-001-001', 'AVAILABLE', '["RESERVABLE", "RFID_READER"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', 'P0', '{"latitude": 40.6011, "longitude": -3.7083}', 'A1', '{"text": "Entrada principal, primera fila"}', '["RESERVED", "EV_ONLY"]', 'group-mad-001', NOW(), NOW(), NOW()),
('evse-mad-001-002', 'loc-mad-001', 'ES', 'ES-CPO', 'ES-CPO-MAD-001-002', 'AVAILABLE', '["RESERVABLE", "RFID_READER"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', 'P0', '{"latitude": 40.6011, "longitude": -3.7083}', 'A2', '{"text": "Entrada principal, segunda fila"}', '["RESERVED", "EV_ONLY"]', 'group-mad-001', NOW(), NOW(), NOW()),
('evse-mad-001-003', 'loc-mad-001', 'ES', 'ES-CPO', 'ES-CPO-MAD-001-003', 'AVAILABLE', '["RESERVABLE", "RFID_READER"]', '[{"id": "3", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', 'P0', '{"latitude": 40.6011, "longitude": -3.7083}', 'A3', '{"text": "Entrada principal, tercera fila"}', '["RESERVED", "EV_ONLY"]', 'group-mad-001', NOW(), NOW(), NOW()),

-- Location: loc-mad-002 (Centro Comercial La Gavia)
('evse-mad-002-001', 'loc-mad-002', 'ES', 'ES-CPO', 'ES-CPO-MAD-002-001', 'AVAILABLE', '["RESERVABLE", "RFID_READER"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', 'P0', '{"latitude": 40.3897, "longitude": -3.6289}', 'B1', '{"text": "Entrada sur, primera fila"}', '["RESERVED", "EV_ONLY"]', 'group-mad-002', NOW(), NOW(), NOW()),
('evse-mad-002-002', 'loc-mad-002', 'ES', 'ES-CPO', 'ES-CPO-MAD-002-002', 'AVAILABLE', '["RESERVABLE", "RFID_READER"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', 'P0', '{"latitude": 40.3897, "longitude": -3.6289}', 'B2', '{"text": "Entrada sur, segunda fila"}', '["RESERVED", "EV_ONLY"]', 'group-mad-002', NOW(), NOW(), NOW()),

-- Location: loc-bcn-001 (Centro Comercial Diagonal Mar)
('evse-bcn-001-001', 'loc-bcn-001', 'ES', 'ES-CPO', 'ES-CPO-BCN-001-001', 'AVAILABLE', '["RESERVABLE", "RFID_READER"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', 'P0', '{"latitude": 41.4089, "longitude": 2.2197}', 'C1', '{"text": "Entrada mar, primera fila"}', '["RESERVED", "EV_ONLY"]', 'group-bcn-001', NOW(), NOW(), NOW()),
('evse-bcn-001-002', 'loc-bcn-001', 'ES', 'ES-CPO', 'ES-CPO-BCN-001-002', 'AVAILABLE', '["RESERVABLE", "RFID_READER"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', 'P0', '{"latitude": 41.4089, "longitude": 2.2197}', 'C2', '{"text": "Entrada mar, segunda fila"}', '["RESERVED", "EV_ONLY"]', 'group-bcn-001', NOW(), NOW(), NOW()),

-- Location: loc-lis-001 (Centro Comercial Colombo)
('evse-lis-001-001', 'loc-lis-001', 'PT', 'ES-CPO', 'ES-CPO-LIS-001-001', 'AVAILABLE', '["RESERVABLE", "RFID_READER"]', '[{"id": "1", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', 'P0', '{"latitude": 38.7223, "longitude": -9.1393}', 'D1', '{"text": "Entrada principal, primeira fila"}', '["RESERVED", "EV_ONLY"]', 'group-lis-001', NOW(), NOW(), NOW()),
('evse-lis-001-002', 'loc-lis-001', 'PT', 'ES-CPO', 'ES-CPO-LIS-001-002', 'AVAILABLE', '["RESERVABLE", "RFID_READER"]', '[{"id": "2", "standard": "IEC_62196_T2", "format": "SOCKET", "power_type": "AC_3_PHASE", "max_voltage": 400, "max_amperage": 32, "max_electric_power": 22000}]', 'P0', '{"latitude": 38.7223, "longitude": -9.1393}', 'D2', '{"text": "Entrada principal, segunda fila"}', '["RESERVED", "EV_ONLY"]', 'group-lis-001', NOW(), NOW(), NOW());
